### ISSUE TITLE
How to get the documentation for the config.ini file.

### ISSUE THREAD

**Issue by vaibhav0195** [gfronza/rabbitmq-alert#29]
I am using python3.7 and installed this beautiful lib of yours.
But when i tried to run --help command to get an in depth information for the args pased i was followed by the error:
 *ModuleNotFoundError: No module named 'argumentsparser'*

can you provide some info about this ?
and also can you please add more docs about the config file.

thanks :)

**Comment by mylk** [comment]
Hello @vaibhav0195 and I'm really sorry for the late reply.

Unfortunately its not yet compatible with python3, but the message doesn't seem related.
Its strange because `argumentsparser` module is an internal module of `rabbitmq-alert`.

If you have cloned the this repo, try running using python2:

```
python2 rabbitmqalert/rabbitmqalert.py  --help
```

Otherwise, refer to the README file's "Execute in a container" section for instructions about how to run it in a container.

Regarding the documentation, indeed, the only option right now is using `--help`.

I'm starting to document all options in a wiki page too and I will update this issue soon.
Feel free to send any update too.

**Comment by mylk** [comment]
Hello again @vaibhav0195.

Thank you again for spotting that essential missing information.

I created a wiki page [here](https://github.com/gfronza/rabbitmq-alert/wiki/Configuration-file) about that. I will also refer to it in the README file.
